version: '3.8'

services:
  market:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: market-app
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - demo-network

  postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-demo_db}
      - POSTGRES_USER=${POSTGRES_USER:-demo_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-demo_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-demo_user} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo-network

volumes:
  postgres_data:

networks:
  demo-network:
    driver: bridge
